export const TASKS_REPOSITORY = Symbol('TASKS_REPOSITORY');
export const COMMENTS_REPOSITORY = Symbol('COMMENTS_REPOSITORY');
export const USERS_TASKS_REPOSITORY = Symbol('USERS_TASKS_REPOSITORY');
export const TASK_AUDIT_LOGS_REPOSITORY = Symbol('TASK_AUDIT_LOGS_REPOSITORY');

export const TASKS_CLIENT = Symbol('TASKS_CLIENT');
