export interface IConfig {
  PORT: number;
  DB_NOTIFICATIONS_SERVICE_PASSWORD: string;
  DB_NOTIFICATIONS_SERVICE_USER: string;
  DB_NOTIFICATIONS_SERVICE_NAME: string;
  DB_NOTIFICATIONS_SERVICE_HOST: string;
  DB_NOTIFICATIONS_SERVICE_PORT: number;
  FRONTEND_ORIGIN: string;
  BROKER_URL: string;
}
