/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTasksAuditLogsRouteImport } from './routes/_authenticated/tasks_/audit-logs'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated/tasks_/$taskId'
import { Route as AuthenticatedTasksAuditLogsUpdateRouteImport } from './routes/_authenticated/tasks_/audit-logs/update'
import { Route as AuthenticatedTasksAuditLogsDeletionRouteImport } from './routes/_authenticated/tasks_/audit-logs/deletion'
import { Route as AuthenticatedTasksAuditLogsCreationRouteImport } from './routes/_authenticated/tasks_/audit-logs/creation'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksAuditLogsRoute =
  AuthenticatedTasksAuditLogsRouteImport.update({
    id: '/tasks_/audit-logs',
    path: '/tasks/audit-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks_/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksAuditLogsUpdateRoute =
  AuthenticatedTasksAuditLogsUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => AuthenticatedTasksAuditLogsRoute,
  } as any)
const AuthenticatedTasksAuditLogsDeletionRoute =
  AuthenticatedTasksAuditLogsDeletionRouteImport.update({
    id: '/deletion',
    path: '/deletion',
    getParentRoute: () => AuthenticatedTasksAuditLogsRoute,
  } as any)
const AuthenticatedTasksAuditLogsCreationRoute =
  AuthenticatedTasksAuditLogsCreationRouteImport.update({
    id: '/creation',
    path: '/creation',
    getParentRoute: () => AuthenticatedTasksAuditLogsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/audit-logs': typeof AuthenticatedTasksAuditLogsRouteWithChildren
  '/tasks/audit-logs/creation': typeof AuthenticatedTasksAuditLogsCreationRoute
  '/tasks/audit-logs/deletion': typeof AuthenticatedTasksAuditLogsDeletionRoute
  '/tasks/audit-logs/update': typeof AuthenticatedTasksAuditLogsUpdateRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/audit-logs': typeof AuthenticatedTasksAuditLogsRouteWithChildren
  '/tasks/audit-logs/creation': typeof AuthenticatedTasksAuditLogsCreationRoute
  '/tasks/audit-logs/deletion': typeof AuthenticatedTasksAuditLogsDeletionRoute
  '/tasks/audit-logs/update': typeof AuthenticatedTasksAuditLogsUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_authenticated/tasks_/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/_authenticated/tasks_/audit-logs': typeof AuthenticatedTasksAuditLogsRouteWithChildren
  '/_authenticated/tasks_/audit-logs/creation': typeof AuthenticatedTasksAuditLogsCreationRoute
  '/_authenticated/tasks_/audit-logs/deletion': typeof AuthenticatedTasksAuditLogsDeletionRoute
  '/_authenticated/tasks_/audit-logs/update': typeof AuthenticatedTasksAuditLogsUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/tasks'
    | '/login'
    | '/register'
    | '/tasks/$taskId'
    | '/tasks/audit-logs'
    | '/tasks/audit-logs/creation'
    | '/tasks/audit-logs/deletion'
    | '/tasks/audit-logs/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/tasks'
    | '/login'
    | '/register'
    | '/tasks/$taskId'
    | '/tasks/audit-logs'
    | '/tasks/audit-logs/creation'
    | '/tasks/audit-logs/deletion'
    | '/tasks/audit-logs/update'
  id:
    | '__root__'
    | '/$'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/tasks'
    | '/_public/login'
    | '/_public/register'
    | '/_authenticated/tasks_/$taskId'
    | '/_authenticated/tasks_/audit-logs'
    | '/_authenticated/tasks_/audit-logs/creation'
    | '/_authenticated/tasks_/audit-logs/deletion'
    | '/_authenticated/tasks_/audit-logs/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks_/audit-logs': {
      id: '/_authenticated/tasks_/audit-logs'
      path: '/tasks/audit-logs'
      fullPath: '/tasks/audit-logs'
      preLoaderRoute: typeof AuthenticatedTasksAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks_/$taskId': {
      id: '/_authenticated/tasks_/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks_/audit-logs/update': {
      id: '/_authenticated/tasks_/audit-logs/update'
      path: '/update'
      fullPath: '/tasks/audit-logs/update'
      preLoaderRoute: typeof AuthenticatedTasksAuditLogsUpdateRouteImport
      parentRoute: typeof AuthenticatedTasksAuditLogsRoute
    }
    '/_authenticated/tasks_/audit-logs/deletion': {
      id: '/_authenticated/tasks_/audit-logs/deletion'
      path: '/deletion'
      fullPath: '/tasks/audit-logs/deletion'
      preLoaderRoute: typeof AuthenticatedTasksAuditLogsDeletionRouteImport
      parentRoute: typeof AuthenticatedTasksAuditLogsRoute
    }
    '/_authenticated/tasks_/audit-logs/creation': {
      id: '/_authenticated/tasks_/audit-logs/creation'
      path: '/creation'
      fullPath: '/tasks/audit-logs/creation'
      preLoaderRoute: typeof AuthenticatedTasksAuditLogsCreationRouteImport
      parentRoute: typeof AuthenticatedTasksAuditLogsRoute
    }
  }
}

interface AuthenticatedTasksAuditLogsRouteChildren {
  AuthenticatedTasksAuditLogsCreationRoute: typeof AuthenticatedTasksAuditLogsCreationRoute
  AuthenticatedTasksAuditLogsDeletionRoute: typeof AuthenticatedTasksAuditLogsDeletionRoute
  AuthenticatedTasksAuditLogsUpdateRoute: typeof AuthenticatedTasksAuditLogsUpdateRoute
}

const AuthenticatedTasksAuditLogsRouteChildren: AuthenticatedTasksAuditLogsRouteChildren =
  {
    AuthenticatedTasksAuditLogsCreationRoute:
      AuthenticatedTasksAuditLogsCreationRoute,
    AuthenticatedTasksAuditLogsDeletionRoute:
      AuthenticatedTasksAuditLogsDeletionRoute,
    AuthenticatedTasksAuditLogsUpdateRoute:
      AuthenticatedTasksAuditLogsUpdateRoute,
  }

const AuthenticatedTasksAuditLogsRouteWithChildren =
  AuthenticatedTasksAuditLogsRoute._addFileChildren(
    AuthenticatedTasksAuditLogsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute
  AuthenticatedTasksAuditLogsRoute: typeof AuthenticatedTasksAuditLogsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
  AuthenticatedTasksAuditLogsRoute:
    AuthenticatedTasksAuditLogsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
