/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SplatRouteRouteImport } from './routes/$/route'
import { Route as PublicLayoutRouteRouteImport } from './routes/_public/_layout/route'
import { Route as AuthenticatedLayoutRouteRouteImport } from './routes/_authenticated/_layout/route'
import { Route as PublicLayoutLoginRouteImport } from './routes/_public/_layout/login'
import { Route as PublicLayoutCadastroRouteImport } from './routes/_public/_layout/cadastro'
import { Route as AuthenticatedLayoutTarefasRouteImport } from './routes/_authenticated/_layout/tarefas'
import { Route as AuthenticatedLayoutTarefasTaskIdRouteImport } from './routes/_authenticated/_layout/tarefas_/$taskId'
import { Route as AuthenticatedLayoutTarefasAuditoriaRouteRouteImport } from './routes/_authenticated/_layout/tarefas_/auditoria/route'
import { Route as AuthenticatedLayoutTarefasAuditoriaExclusaoRouteImport } from './routes/_authenticated/_layout/tarefas_/auditoria/exclusao'
import { Route as AuthenticatedLayoutTarefasAuditoriaCriacaoRouteImport } from './routes/_authenticated/_layout/tarefas_/auditoria/criacao'
import { Route as AuthenticatedLayoutTarefasAuditoriaAtualizacaoRouteImport } from './routes/_authenticated/_layout/tarefas_/auditoria/atualizacao'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRouteRoute = SplatRouteRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRouteRoute = PublicLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedLayoutRouteRoute =
  AuthenticatedLayoutRouteRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicLayoutLoginRoute = PublicLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicLayoutRouteRoute,
} as any)
const PublicLayoutCadastroRoute = PublicLayoutCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => PublicLayoutRouteRoute,
} as any)
const AuthenticatedLayoutTarefasRoute =
  AuthenticatedLayoutTarefasRouteImport.update({
    id: '/tarefas',
    path: '/tarefas',
    getParentRoute: () => AuthenticatedLayoutRouteRoute,
  } as any)
const AuthenticatedLayoutTarefasTaskIdRoute =
  AuthenticatedLayoutTarefasTaskIdRouteImport.update({
    id: '/tarefas_/$taskId',
    path: '/tarefas/$taskId',
    getParentRoute: () => AuthenticatedLayoutRouteRoute,
  } as any)
const AuthenticatedLayoutTarefasAuditoriaRouteRoute =
  AuthenticatedLayoutTarefasAuditoriaRouteRouteImport.update({
    id: '/tarefas_/auditoria',
    path: '/tarefas/auditoria',
    getParentRoute: () => AuthenticatedLayoutRouteRoute,
  } as any)
const AuthenticatedLayoutTarefasAuditoriaExclusaoRoute =
  AuthenticatedLayoutTarefasAuditoriaExclusaoRouteImport.update({
    id: '/exclusao',
    path: '/exclusao',
    getParentRoute: () => AuthenticatedLayoutTarefasAuditoriaRouteRoute,
  } as any)
const AuthenticatedLayoutTarefasAuditoriaCriacaoRoute =
  AuthenticatedLayoutTarefasAuditoriaCriacaoRouteImport.update({
    id: '/criacao',
    path: '/criacao',
    getParentRoute: () => AuthenticatedLayoutTarefasAuditoriaRouteRoute,
  } as any)
const AuthenticatedLayoutTarefasAuditoriaAtualizacaoRoute =
  AuthenticatedLayoutTarefasAuditoriaAtualizacaoRouteImport.update({
    id: '/atualizacao',
    path: '/atualizacao',
    getParentRoute: () => AuthenticatedLayoutTarefasAuditoriaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRouteRoute
  '/tarefas': typeof AuthenticatedLayoutTarefasRoute
  '/cadastro': typeof PublicLayoutCadastroRoute
  '/login': typeof PublicLayoutLoginRoute
  '/tarefas/auditoria': typeof AuthenticatedLayoutTarefasAuditoriaRouteRouteWithChildren
  '/tarefas/$taskId': typeof AuthenticatedLayoutTarefasTaskIdRoute
  '/tarefas/auditoria/atualizacao': typeof AuthenticatedLayoutTarefasAuditoriaAtualizacaoRoute
  '/tarefas/auditoria/criacao': typeof AuthenticatedLayoutTarefasAuditoriaCriacaoRoute
  '/tarefas/auditoria/exclusao': typeof AuthenticatedLayoutTarefasAuditoriaExclusaoRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRouteRoute
  '/tarefas': typeof AuthenticatedLayoutTarefasRoute
  '/cadastro': typeof PublicLayoutCadastroRoute
  '/login': typeof PublicLayoutLoginRoute
  '/tarefas/auditoria': typeof AuthenticatedLayoutTarefasAuditoriaRouteRouteWithChildren
  '/tarefas/$taskId': typeof AuthenticatedLayoutTarefasTaskIdRoute
  '/tarefas/auditoria/atualizacao': typeof AuthenticatedLayoutTarefasAuditoriaAtualizacaoRoute
  '/tarefas/auditoria/criacao': typeof AuthenticatedLayoutTarefasAuditoriaCriacaoRoute
  '/tarefas/auditoria/exclusao': typeof AuthenticatedLayoutTarefasAuditoriaExclusaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRouteRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteRouteWithChildren
  '/_public/_layout': typeof PublicLayoutRouteRouteWithChildren
  '/_authenticated/_layout/tarefas': typeof AuthenticatedLayoutTarefasRoute
  '/_public/_layout/cadastro': typeof PublicLayoutCadastroRoute
  '/_public/_layout/login': typeof PublicLayoutLoginRoute
  '/_authenticated/_layout/tarefas_/auditoria': typeof AuthenticatedLayoutTarefasAuditoriaRouteRouteWithChildren
  '/_authenticated/_layout/tarefas_/$taskId': typeof AuthenticatedLayoutTarefasTaskIdRoute
  '/_authenticated/_layout/tarefas_/auditoria/atualizacao': typeof AuthenticatedLayoutTarefasAuditoriaAtualizacaoRoute
  '/_authenticated/_layout/tarefas_/auditoria/criacao': typeof AuthenticatedLayoutTarefasAuditoriaCriacaoRoute
  '/_authenticated/_layout/tarefas_/auditoria/exclusao': typeof AuthenticatedLayoutTarefasAuditoriaExclusaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/tarefas'
    | '/cadastro'
    | '/login'
    | '/tarefas/auditoria'
    | '/tarefas/$taskId'
    | '/tarefas/auditoria/atualizacao'
    | '/tarefas/auditoria/criacao'
    | '/tarefas/auditoria/exclusao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/tarefas'
    | '/cadastro'
    | '/login'
    | '/tarefas/auditoria'
    | '/tarefas/$taskId'
    | '/tarefas/auditoria/atualizacao'
    | '/tarefas/auditoria/criacao'
    | '/tarefas/auditoria/exclusao'
  id:
    | '__root__'
    | '/$'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_layout'
    | '/_public/_layout'
    | '/_authenticated/_layout/tarefas'
    | '/_public/_layout/cadastro'
    | '/_public/_layout/login'
    | '/_authenticated/_layout/tarefas_/auditoria'
    | '/_authenticated/_layout/tarefas_/$taskId'
    | '/_authenticated/_layout/tarefas_/auditoria/atualizacao'
    | '/_authenticated/_layout/tarefas_/auditoria/criacao'
    | '/_authenticated/_layout/tarefas_/auditoria/exclusao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRouteRoute: typeof SplatRouteRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_layout': {
      id: '/_public/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/_layout/login': {
      id: '/_public/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLayoutLoginRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_public/_layout/cadastro': {
      id: '/_public/_layout/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof PublicLayoutCadastroRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_authenticated/_layout/tarefas': {
      id: '/_authenticated/_layout/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedLayoutTarefasRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteRoute
    }
    '/_authenticated/_layout/tarefas_/$taskId': {
      id: '/_authenticated/_layout/tarefas_/$taskId'
      path: '/tarefas/$taskId'
      fullPath: '/tarefas/$taskId'
      preLoaderRoute: typeof AuthenticatedLayoutTarefasTaskIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteRoute
    }
    '/_authenticated/_layout/tarefas_/auditoria': {
      id: '/_authenticated/_layout/tarefas_/auditoria'
      path: '/tarefas/auditoria'
      fullPath: '/tarefas/auditoria'
      preLoaderRoute: typeof AuthenticatedLayoutTarefasAuditoriaRouteRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteRoute
    }
    '/_authenticated/_layout/tarefas_/auditoria/exclusao': {
      id: '/_authenticated/_layout/tarefas_/auditoria/exclusao'
      path: '/exclusao'
      fullPath: '/tarefas/auditoria/exclusao'
      preLoaderRoute: typeof AuthenticatedLayoutTarefasAuditoriaExclusaoRouteImport
      parentRoute: typeof AuthenticatedLayoutTarefasAuditoriaRouteRoute
    }
    '/_authenticated/_layout/tarefas_/auditoria/criacao': {
      id: '/_authenticated/_layout/tarefas_/auditoria/criacao'
      path: '/criacao'
      fullPath: '/tarefas/auditoria/criacao'
      preLoaderRoute: typeof AuthenticatedLayoutTarefasAuditoriaCriacaoRouteImport
      parentRoute: typeof AuthenticatedLayoutTarefasAuditoriaRouteRoute
    }
    '/_authenticated/_layout/tarefas_/auditoria/atualizacao': {
      id: '/_authenticated/_layout/tarefas_/auditoria/atualizacao'
      path: '/atualizacao'
      fullPath: '/tarefas/auditoria/atualizacao'
      preLoaderRoute: typeof AuthenticatedLayoutTarefasAuditoriaAtualizacaoRouteImport
      parentRoute: typeof AuthenticatedLayoutTarefasAuditoriaRouteRoute
    }
  }
}

interface AuthenticatedLayoutTarefasAuditoriaRouteRouteChildren {
  AuthenticatedLayoutTarefasAuditoriaAtualizacaoRoute: typeof AuthenticatedLayoutTarefasAuditoriaAtualizacaoRoute
  AuthenticatedLayoutTarefasAuditoriaCriacaoRoute: typeof AuthenticatedLayoutTarefasAuditoriaCriacaoRoute
  AuthenticatedLayoutTarefasAuditoriaExclusaoRoute: typeof AuthenticatedLayoutTarefasAuditoriaExclusaoRoute
}

const AuthenticatedLayoutTarefasAuditoriaRouteRouteChildren: AuthenticatedLayoutTarefasAuditoriaRouteRouteChildren =
  {
    AuthenticatedLayoutTarefasAuditoriaAtualizacaoRoute:
      AuthenticatedLayoutTarefasAuditoriaAtualizacaoRoute,
    AuthenticatedLayoutTarefasAuditoriaCriacaoRoute:
      AuthenticatedLayoutTarefasAuditoriaCriacaoRoute,
    AuthenticatedLayoutTarefasAuditoriaExclusaoRoute:
      AuthenticatedLayoutTarefasAuditoriaExclusaoRoute,
  }

const AuthenticatedLayoutTarefasAuditoriaRouteRouteWithChildren =
  AuthenticatedLayoutTarefasAuditoriaRouteRoute._addFileChildren(
    AuthenticatedLayoutTarefasAuditoriaRouteRouteChildren,
  )

interface AuthenticatedLayoutRouteRouteChildren {
  AuthenticatedLayoutTarefasRoute: typeof AuthenticatedLayoutTarefasRoute
  AuthenticatedLayoutTarefasAuditoriaRouteRoute: typeof AuthenticatedLayoutTarefasAuditoriaRouteRouteWithChildren
  AuthenticatedLayoutTarefasTaskIdRoute: typeof AuthenticatedLayoutTarefasTaskIdRoute
}

const AuthenticatedLayoutRouteRouteChildren: AuthenticatedLayoutRouteRouteChildren =
  {
    AuthenticatedLayoutTarefasRoute: AuthenticatedLayoutTarefasRoute,
    AuthenticatedLayoutTarefasAuditoriaRouteRoute:
      AuthenticatedLayoutTarefasAuditoriaRouteRouteWithChildren,
    AuthenticatedLayoutTarefasTaskIdRoute:
      AuthenticatedLayoutTarefasTaskIdRoute,
  }

const AuthenticatedLayoutRouteRouteWithChildren =
  AuthenticatedLayoutRouteRoute._addFileChildren(
    AuthenticatedLayoutRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLayoutRouteRoute: typeof AuthenticatedLayoutRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLayoutRouteRoute: AuthenticatedLayoutRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicLayoutRouteRouteChildren {
  PublicLayoutCadastroRoute: typeof PublicLayoutCadastroRoute
  PublicLayoutLoginRoute: typeof PublicLayoutLoginRoute
}

const PublicLayoutRouteRouteChildren: PublicLayoutRouteRouteChildren = {
  PublicLayoutCadastroRoute: PublicLayoutCadastroRoute,
  PublicLayoutLoginRoute: PublicLayoutLoginRoute,
}

const PublicLayoutRouteRouteWithChildren =
  PublicLayoutRouteRoute._addFileChildren(PublicLayoutRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicLayoutRouteRoute: typeof PublicLayoutRouteRouteWithChildren
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLayoutRouteRoute: PublicLayoutRouteRouteWithChildren,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRouteRoute: SplatRouteRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
