/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicLayoutRouteRouteImport } from './routes/_public/_layout/route'
import { Route as AuthenticatedLayoutRouteRouteImport } from './routes/_authenticated/_layout/route'
import { Route as PublicLayoutRegisterRouteImport } from './routes/_public/_layout/register'
import { Route as PublicLayoutLoginRouteImport } from './routes/_public/_layout/login'
import { Route as AuthenticatedLayoutTasksRouteImport } from './routes/_authenticated/_layout/tasks'
import { Route as AuthenticatedLayoutTasksTaskIdRouteImport } from './routes/_authenticated/_layout/tasks_/$taskId'
import { Route as AuthenticatedLayoutTasksAuditLogsRouteRouteImport } from './routes/_authenticated/_layout/tasks_/audit-logs/route'
import { Route as AuthenticatedLayoutTasksAuditLogsUpdateRouteImport } from './routes/_authenticated/_layout/tasks_/audit-logs/update'
import { Route as AuthenticatedLayoutTasksAuditLogsDeletionRouteImport } from './routes/_authenticated/_layout/tasks_/audit-logs/deletion'
import { Route as AuthenticatedLayoutTasksAuditLogsCreationRouteImport } from './routes/_authenticated/_layout/tasks_/audit-logs/creation'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRouteRoute = PublicLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedLayoutRouteRoute =
  AuthenticatedLayoutRouteRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicLayoutRegisterRoute = PublicLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicLayoutRouteRoute,
} as any)
const PublicLayoutLoginRoute = PublicLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicLayoutRouteRoute,
} as any)
const AuthenticatedLayoutTasksRoute =
  AuthenticatedLayoutTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedLayoutRouteRoute,
  } as any)
const AuthenticatedLayoutTasksTaskIdRoute =
  AuthenticatedLayoutTasksTaskIdRouteImport.update({
    id: '/tasks_/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedLayoutRouteRoute,
  } as any)
const AuthenticatedLayoutTasksAuditLogsRouteRoute =
  AuthenticatedLayoutTasksAuditLogsRouteRouteImport.update({
    id: '/tasks_/audit-logs',
    path: '/tasks/audit-logs',
    getParentRoute: () => AuthenticatedLayoutRouteRoute,
  } as any)
const AuthenticatedLayoutTasksAuditLogsUpdateRoute =
  AuthenticatedLayoutTasksAuditLogsUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => AuthenticatedLayoutTasksAuditLogsRouteRoute,
  } as any)
const AuthenticatedLayoutTasksAuditLogsDeletionRoute =
  AuthenticatedLayoutTasksAuditLogsDeletionRouteImport.update({
    id: '/deletion',
    path: '/deletion',
    getParentRoute: () => AuthenticatedLayoutTasksAuditLogsRouteRoute,
  } as any)
const AuthenticatedLayoutTasksAuditLogsCreationRoute =
  AuthenticatedLayoutTasksAuditLogsCreationRouteImport.update({
    id: '/creation',
    path: '/creation',
    getParentRoute: () => AuthenticatedLayoutTasksAuditLogsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/tasks': typeof AuthenticatedLayoutTasksRoute
  '/login': typeof PublicLayoutLoginRoute
  '/register': typeof PublicLayoutRegisterRoute
  '/tasks/audit-logs': typeof AuthenticatedLayoutTasksAuditLogsRouteRouteWithChildren
  '/tasks/$taskId': typeof AuthenticatedLayoutTasksTaskIdRoute
  '/tasks/audit-logs/creation': typeof AuthenticatedLayoutTasksAuditLogsCreationRoute
  '/tasks/audit-logs/deletion': typeof AuthenticatedLayoutTasksAuditLogsDeletionRoute
  '/tasks/audit-logs/update': typeof AuthenticatedLayoutTasksAuditLogsUpdateRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/tasks': typeof AuthenticatedLayoutTasksRoute
  '/login': typeof PublicLayoutLoginRoute
  '/register': typeof PublicLayoutRegisterRoute
  '/tasks/audit-logs': typeof AuthenticatedLayoutTasksAuditLogsRouteRouteWithChildren
  '/tasks/$taskId': typeof AuthenticatedLayoutTasksTaskIdRoute
  '/tasks/audit-logs/creation': typeof AuthenticatedLayoutTasksAuditLogsCreationRoute
  '/tasks/audit-logs/deletion': typeof AuthenticatedLayoutTasksAuditLogsDeletionRoute
  '/tasks/audit-logs/update': typeof AuthenticatedLayoutTasksAuditLogsUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteRouteWithChildren
  '/_public/_layout': typeof PublicLayoutRouteRouteWithChildren
  '/_authenticated/_layout/tasks': typeof AuthenticatedLayoutTasksRoute
  '/_public/_layout/login': typeof PublicLayoutLoginRoute
  '/_public/_layout/register': typeof PublicLayoutRegisterRoute
  '/_authenticated/_layout/tasks_/audit-logs': typeof AuthenticatedLayoutTasksAuditLogsRouteRouteWithChildren
  '/_authenticated/_layout/tasks_/$taskId': typeof AuthenticatedLayoutTasksTaskIdRoute
  '/_authenticated/_layout/tasks_/audit-logs/creation': typeof AuthenticatedLayoutTasksAuditLogsCreationRoute
  '/_authenticated/_layout/tasks_/audit-logs/deletion': typeof AuthenticatedLayoutTasksAuditLogsDeletionRoute
  '/_authenticated/_layout/tasks_/audit-logs/update': typeof AuthenticatedLayoutTasksAuditLogsUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/tasks'
    | '/login'
    | '/register'
    | '/tasks/audit-logs'
    | '/tasks/$taskId'
    | '/tasks/audit-logs/creation'
    | '/tasks/audit-logs/deletion'
    | '/tasks/audit-logs/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/tasks'
    | '/login'
    | '/register'
    | '/tasks/audit-logs'
    | '/tasks/$taskId'
    | '/tasks/audit-logs/creation'
    | '/tasks/audit-logs/deletion'
    | '/tasks/audit-logs/update'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/$'
    | '/_authenticated/_layout'
    | '/_public/_layout'
    | '/_authenticated/_layout/tasks'
    | '/_public/_layout/login'
    | '/_public/_layout/register'
    | '/_authenticated/_layout/tasks_/audit-logs'
    | '/_authenticated/_layout/tasks_/$taskId'
    | '/_authenticated/_layout/tasks_/audit-logs/creation'
    | '/_authenticated/_layout/tasks_/audit-logs/deletion'
    | '/_authenticated/_layout/tasks_/audit-logs/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_layout': {
      id: '/_public/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/_layout/register': {
      id: '/_public/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicLayoutRegisterRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_public/_layout/login': {
      id: '/_public/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLayoutLoginRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_authenticated/_layout/tasks': {
      id: '/_authenticated/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedLayoutTasksRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteRoute
    }
    '/_authenticated/_layout/tasks_/$taskId': {
      id: '/_authenticated/_layout/tasks_/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedLayoutTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteRoute
    }
    '/_authenticated/_layout/tasks_/audit-logs': {
      id: '/_authenticated/_layout/tasks_/audit-logs'
      path: '/tasks/audit-logs'
      fullPath: '/tasks/audit-logs'
      preLoaderRoute: typeof AuthenticatedLayoutTasksAuditLogsRouteRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteRoute
    }
    '/_authenticated/_layout/tasks_/audit-logs/update': {
      id: '/_authenticated/_layout/tasks_/audit-logs/update'
      path: '/update'
      fullPath: '/tasks/audit-logs/update'
      preLoaderRoute: typeof AuthenticatedLayoutTasksAuditLogsUpdateRouteImport
      parentRoute: typeof AuthenticatedLayoutTasksAuditLogsRouteRoute
    }
    '/_authenticated/_layout/tasks_/audit-logs/deletion': {
      id: '/_authenticated/_layout/tasks_/audit-logs/deletion'
      path: '/deletion'
      fullPath: '/tasks/audit-logs/deletion'
      preLoaderRoute: typeof AuthenticatedLayoutTasksAuditLogsDeletionRouteImport
      parentRoute: typeof AuthenticatedLayoutTasksAuditLogsRouteRoute
    }
    '/_authenticated/_layout/tasks_/audit-logs/creation': {
      id: '/_authenticated/_layout/tasks_/audit-logs/creation'
      path: '/creation'
      fullPath: '/tasks/audit-logs/creation'
      preLoaderRoute: typeof AuthenticatedLayoutTasksAuditLogsCreationRouteImport
      parentRoute: typeof AuthenticatedLayoutTasksAuditLogsRouteRoute
    }
  }
}

interface AuthenticatedLayoutTasksAuditLogsRouteRouteChildren {
  AuthenticatedLayoutTasksAuditLogsCreationRoute: typeof AuthenticatedLayoutTasksAuditLogsCreationRoute
  AuthenticatedLayoutTasksAuditLogsDeletionRoute: typeof AuthenticatedLayoutTasksAuditLogsDeletionRoute
  AuthenticatedLayoutTasksAuditLogsUpdateRoute: typeof AuthenticatedLayoutTasksAuditLogsUpdateRoute
}

const AuthenticatedLayoutTasksAuditLogsRouteRouteChildren: AuthenticatedLayoutTasksAuditLogsRouteRouteChildren =
  {
    AuthenticatedLayoutTasksAuditLogsCreationRoute:
      AuthenticatedLayoutTasksAuditLogsCreationRoute,
    AuthenticatedLayoutTasksAuditLogsDeletionRoute:
      AuthenticatedLayoutTasksAuditLogsDeletionRoute,
    AuthenticatedLayoutTasksAuditLogsUpdateRoute:
      AuthenticatedLayoutTasksAuditLogsUpdateRoute,
  }

const AuthenticatedLayoutTasksAuditLogsRouteRouteWithChildren =
  AuthenticatedLayoutTasksAuditLogsRouteRoute._addFileChildren(
    AuthenticatedLayoutTasksAuditLogsRouteRouteChildren,
  )

interface AuthenticatedLayoutRouteRouteChildren {
  AuthenticatedLayoutTasksRoute: typeof AuthenticatedLayoutTasksRoute
  AuthenticatedLayoutTasksAuditLogsRouteRoute: typeof AuthenticatedLayoutTasksAuditLogsRouteRouteWithChildren
  AuthenticatedLayoutTasksTaskIdRoute: typeof AuthenticatedLayoutTasksTaskIdRoute
}

const AuthenticatedLayoutRouteRouteChildren: AuthenticatedLayoutRouteRouteChildren =
  {
    AuthenticatedLayoutTasksRoute: AuthenticatedLayoutTasksRoute,
    AuthenticatedLayoutTasksAuditLogsRouteRoute:
      AuthenticatedLayoutTasksAuditLogsRouteRouteWithChildren,
    AuthenticatedLayoutTasksTaskIdRoute: AuthenticatedLayoutTasksTaskIdRoute,
  }

const AuthenticatedLayoutRouteRouteWithChildren =
  AuthenticatedLayoutRouteRoute._addFileChildren(
    AuthenticatedLayoutRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLayoutRouteRoute: typeof AuthenticatedLayoutRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLayoutRouteRoute: AuthenticatedLayoutRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicLayoutRouteRouteChildren {
  PublicLayoutLoginRoute: typeof PublicLayoutLoginRoute
  PublicLayoutRegisterRoute: typeof PublicLayoutRegisterRoute
}

const PublicLayoutRouteRouteChildren: PublicLayoutRouteRouteChildren = {
  PublicLayoutLoginRoute: PublicLayoutLoginRoute,
  PublicLayoutRegisterRoute: PublicLayoutRegisterRoute,
}

const PublicLayoutRouteRouteWithChildren =
  PublicLayoutRouteRoute._addFileChildren(PublicLayoutRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicLayoutRouteRoute: typeof PublicLayoutRouteRouteWithChildren
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLayoutRouteRoute: PublicLayoutRouteRouteWithChildren,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
